added phone number validator
taldor-ltd/tld-angular-fnd pull request #14
Opened 2020-03-09 17:47 UTC by LiorBaraban

@benshabatnoam would appreciate your review

2020-03-11 09:22 UTC, benshabatnoam requested changes
Missing `readme.md` changes

2020-11-02 13:12 UTC, oferah approved these changes

2020-11-02 13:13 UTC, oferah approved these changes

2021-10-13 15:10 UTC, LiorBaraban commented
יאללה אני ממזג את הפול ריקווסט הזה או מה?
שנתיים ייבשתם אותי
❤️ סתם
געגועיי
@oferah @benshabatnoam

2021-10-13 19:30 UTC, benshabatnoam commented
> יאללה אני ממזג את הפול ריקווסט הזה או מה? שנתיים ייבשתם אותי ❤️ סתם געגועיי @oferah @benshabatnoam
@LiorBaraban 
אתה יודע כמה זמן אני מחכה לזה, הגיעה הזמן 🤣
טוב לשמוע ממך!

2022-02-15 20:35 UTC, closed without merging